### ISSUE TITLE
Pygments can't parse unknown language: ruby

### ISSUE THREAD

**Issue by manicolosi** [imathis/octopress#1173]
Here's the example I'm trying to get working:

``````
``` ruby
class Fixnum
  def prime?
    ('1' * self) !~ /^1?$|^(11+?)\1+$/
  end
end
```
``````

And I'm getting this error when I run `rake generate`:

```
## Generating Site with Jekyll
identical source/stylesheets/screen.css
Configuration from /home/mark/src/octopress/_config.yml
Building site: source -> public
/home/mark/src/octopress/plugins/pygments_code.rb:27:in `rescue in pygments': Pygments can't parse unknown language: clojure. (RuntimeError)
        from /home/mark/src/octopress/plugins/pygments_code.rb:24:in `pygments'
        from /home/mark/src/octopress/plugins/pygments_code.rb:14:in `highlight'
        from /home/mark/src/octopress/plugins/backtick_code_block.rb:37:in `block in render_code_block'
        from /home/mark/src/octopress/plugins/backtick_code_block.rb:13:in `gsub'
        from /home/mark/src/octopress/plugins/backtick_code_block.rb:13:in `render_code_block'
        from /home/mark/src/octopress/plugins/octopress_filters.rb:12:in `pre_filter'
        from /home/mark/src/octopress/plugins/octopress_filters.rb:28:in `pre_render'
        from /home/mark/src/octopress/plugins/post_filters.rb:112:in `block in pre_render'
        from /home/mark/src/octopress/plugins/post_filters.rb:111:in `each'
        from /home/mark/src/octopress/plugins/post_filters.rb:111:in `pre_render'
        from /home/mark/src/octopress/plugins/post_filters.rb:166:in `do_layout'
        from /home/mark/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/post.rb:195:in `render'
        from /home/mark/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:200:in `block in render'
        from /home/mark/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:199:in `each'
        from /home/mark/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:199:in `render'
        from /home/mark/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:41:in `process'
        from /home/mark/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/bin/jekyll:264:in `<top (required)>'
        from /home/mark/.rbenv/versions/1.9.3-p194/bin/jekyll:23:in `load'
        from /home/mark/.rbenv/versions/1.9.3-p194/bin/jekyll:23:in `<main>'
```

I've also tried other language (python/clojure/etc), but I get the same error messages. I'm on ArchLinux and have followed the installation instructions almost exactly.

I know Pygments uses Python, so maybe this helps:

```
● master ~/src/octopress % python --version
Python 3.3.0
● master ~/src/octopress % python2 --version
Python 2.7.3
```

Thanks for help!

**Comment by duffqiu** [comment]
i found that we have to use python2.7.x instead of python.x

**Comment by duffqiu** [comment]
i found that we have to use python2.7.x instead of python3.x
