### ISSUE TITLE
rake script fail when deployed to production environment

### ISSUE THREAD

**Issue by denvazh** [imathis/octopress#1439]
I faced this error when tried to normally deploy application to heroku ( as it was suggested in the documentation ):

```
Could not detect rake tasks
       ensure you can run `$ bundle exec rake -P` against your app with no environment variables present
       and using the production group of your Gemfile.
       This may be intentional, if you expected rake tasks to be run
       cancel the build (CTRL+C) and fix the error then commit the fix:
       rake aborted!
       cannot load such file -- stringex
       /tmp/build_73690480-fdc4-4127-927b-7b12d2733cf6/Rakefile:3:in `require'
       /tmp/build_73690480-fdc4-4127-927b-7b12d2733cf6/Rakefile:3:in `<top (required)>'
       /tmp/build_73690480-fdc4-4127-927b-7b12d2733cf6/vendor/ruby-2.0.0/lib/ruby/2.0.0/rake/rake_module.rb:25:in `load'
       /tmp/build_73690480-fdc4-4127-927b-7b12d2733cf6/vendor/ruby-2.0.0/lib/ruby/2.0.0/rake/rake_module.rb:25:in `load_rakefile'
       /tmp/build_73690480-fdc4-4127-927b-7b12d2733cf6/vendor/ruby-2.0.0/lib/ruby/2.0.0/rake/application.rb:604:in `raw_load_rakefile'
       /tmp/build_73690480-fdc4-4127-927b-7b12d2733cf6/vendor/ruby-2.0.0/lib/ruby/2.0.0/rake/application.rb:89:in `block in load_rakefile'
       /tmp/build_73690480-fdc4-4127-927b-7b12d2733cf6/vendor/ruby-2.0.0/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_handling'
       /tmp/build_73690480-fdc4-4127-927b-7b12d2733cf6/vendor/ruby-2.0.0/lib/ruby/2.0.0/rake/application.rb:88:in `load_rakefile'
       /tmp/build_73690480-fdc4-4127-927b-7b12d2733cf6/vendor/ruby-2.0.0/lib/ruby/2.0.0/rake/application.rb:72:in `block in run'
       /tmp/build_73690480-fdc4-4127-927b-7b12d2733cf6/vendor/ruby-2.0.0/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_handling'
       /tmp/build_73690480-fdc4-4127-927b-7b12d2733cf6/vendor/ruby-2.0.0/lib/ruby/2.0.0/rake/application.rb:70:in `run'
```

I looked inside Rakefile and found these lines:

```
require "rubygems"
require "bundler/setup"
require "stringex"
```

Obviously, it is expected to be installed. However, in Gemfile it is set to be installed only for development, hence the error.

```
group :development do
       [...]
       gem 'stringex', '~> 1.4.0'
end
```

If stringex is used not only for development, then it should be moved out from development group.

**Comment by ksingh7** [comment]
@danielricecodes thanks your fix did the trick , you rock :+1:
