### ISSUE TITLE
 Pygments can't parse unknown language: func. (Cannot generate)

### ISSUE THREAD

**Issue by cuixin** [imathis/octopress#1465]
```
cuixin.github.com git:(source) ✗ bundle install
Using rake (0.9.2.2)
Using RedCloth (4.2.9)
Using chunky_png (1.2.5)
Using fast-stemmer (1.0.1)
Using classifier (1.3.3)
Using fssm (0.2.9)
Using sass (3.2.9)
Using compass (0.12.2)
Using directory_watcher (1.4.1)
Using haml (3.1.7)
Using kramdown (0.13.8)
Using liquid (2.3.0)
Using syntax (1.0.0)
Using maruku (0.6.1)
Using posix-spawn (0.3.6)
Using yajl-ruby (1.1.0)
Using pygments.rb (0.3.4)
Using jekyll (0.12.0)
Using rack (1.5.2)
Using rack-protection (1.5.0)
Using rb-fsevent (0.9.1)
Using rdiscount (2.0.7.3)
Using rubypants (0.2.0)
Using sass-globbing (1.0.0)
Using tilt (1.3.7)
Using sinatra (1.4.2)
Using stringex (1.4.0)
Using bundler (1.5.1)
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

```
cuixin.github.com git:(source) ✗ rake generate
## Generating Site with Jekyll
identical source/stylesheets/screen.css
Configuration from /Users/steven/Work/github/cuixin.github.com/_config.yml
Building site: source -> public
/Users/steven/Work/github/cuixin.github.com/plugins/pygments_code.rb:27:in `rescue in pygments': Pygments can't parse unknown language: func. (RuntimeError)
    from /Users/steven/Work/github/cuixin.github.com/plugins/pygments_code.rb:24:in `pygments'
    from /Users/steven/Work/github/cuixin.github.com/plugins/pygments_code.rb:14:in `highlight'
    from /Users/steven/Work/github/cuixin.github.com/plugins/backtick_code_block.rb:37:in `block in render_code_block'
    from /Users/steven/Work/github/cuixin.github.com/plugins/backtick_code_block.rb:13:in `gsub'
    from /Users/steven/Work/github/cuixin.github.com/plugins/backtick_code_block.rb:13:in `render_code_block'
    from /Users/steven/Work/github/cuixin.github.com/plugins/octopress_filters.rb:12:in `pre_filter'
    from /Users/steven/Work/github/cuixin.github.com/plugins/octopress_filters.rb:28:in `pre_render'
    from /Users/steven/Work/github/cuixin.github.com/plugins/post_filters.rb:112:in `block in pre_render'
    from /Users/steven/Work/github/cuixin.github.com/plugins/post_filters.rb:111:in `each'
    from /Users/steven/Work/github/cuixin.github.com/plugins/post_filters.rb:111:in `pre_render'
    from /Users/steven/Work/github/cuixin.github.com/plugins/post_filters.rb:166:in `do_layout'
    from /Users/steven/.rvm/gems/ruby-1.9.3-p484/gems/jekyll-0.12.0/lib/jekyll/post.rb:195:in `render'
    from /Users/steven/.rvm/gems/ruby-1.9.3-p484/gems/jekyll-0.12.0/lib/jekyll/site.rb:200:in `block in render'
    from /Users/steven/.rvm/gems/ruby-1.9.3-p484/gems/jekyll-0.12.0/lib/jekyll/site.rb:199:in `each'
    from /Users/steven/.rvm/gems/ruby-1.9.3-p484/gems/jekyll-0.12.0/lib/jekyll/site.rb:199:in `render'
    from /Users/steven/.rvm/gems/ruby-1.9.3-p484/gems/jekyll-0.12.0/lib/jekyll/site.rb:41:in `process'
    from /Users/steven/.rvm/gems/ruby-1.9.3-p484/gems/jekyll-0.12.0/bin/jekyll:264:in `<top (required)>'
    from /Users/steven/.rvm/gems/ruby-1.9.3-p484/bin/jekyll:23:in `load'
    from /Users/steven/.rvm/gems/ruby-1.9.3-p484/bin/jekyll:23:in `<main>'
    from /Users/steven/.rvm/gems/ruby-1.9.3-p484/bin/ruby_executable_hooks:15:in `eval'
    from /Users/steven/.rvm/gems/ruby-1.9.3-p484/bin/ruby_executable_hooks:15:in `<main>'
```

```
cuixin.github.com git:(source) ✗ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-darwin13.0.0]
```

```
cuixin.github.com git:(source) ✗ python --version
Python 2.7.5
```

**Comment by SunDi3yansyah** [comment]
yes, it says parkr all it has to do with the backtick code blocks or highlight tags

this my research, I use backtick code blocks

##### before

![screenshot from 2014-09-07 03 09 41](https://cloud.githubusercontent.com/assets/3952281/4176411/65f8a042-3602-11e4-8535-be7e58ac76d8.png)

##### after

![screenshot from 2014-09-07 03 09 54](https://cloud.githubusercontent.com/assets/3952281/4176421/1975e24c-3603-11e4-9e1a-6919036273db.png)

**Comment by draptik** [comment]
still a problem (2016):

```
(source *%>) $ python --version
Python 2.7.11
 (source *%>) $ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
```

**Comment by al03** [comment]
+1

**Comment by anoobbava** [comment]
same issue when used ``` for codeblock, for used for the first time , no issues. Only issue happens when the ``` used for the second time

**Comment by anoobbava** [comment]
Hi, Got a workaround for this issue
--------------------------
```gem install bundler```
```gem install rails```
this is the issue. instead of using one line syntax, make use of below syntax, and it is worked for me.
like put 3 tilde symbols  in the first line and in the next line the code and in the next line put 3 tilde symbols also so the output is like 
```
gem install bundler
```

```
gem install bundler
```
