### ISSUE TITLE
Dependency Error:  Yikes! It looks like you don't have jekyll-coffeescript installed.

### ISSUE THREAD

**Issue by joseluisq** [imathis/octopress#1695]
Hi, I have `Fedora 20 x86_64`

Ruby and Gems versions:

``` sh
$ ruby -v
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux]

$ gem -v
2.4.5
```

Bundle:

``` sh
$ bundle install
Using rake 10.4.2
Using RedCloth 4.2.9
Using blankslate 2.1.2.4
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.0
Using chunky_png 1.3.3
Using fast-stemmer 1.0.2
Using classifier-reborn 2.0.2
Using coffee-script-source 1.8.0
Using execjs 2.2.2
Using coffee-script 2.3.0
Using colorator 0.1
Using fssm 0.2.10
Using sass 3.2.19
Using compass 0.12.7
Using ffi 1.9.6
Using tilt 1.4.1
Using haml 4.0.6
Using jekyll-coffeescript 1.0.1
Using jekyll-gist 1.1.0
Using jekyll-paginate 1.1.0
Using jekyll-sass-converter 1.2.1
Using rb-fsevent 0.9.4
Using rb-inotify 0.9.5
Using listen 2.8.3
Using jekyll-watch 1.2.0
Using kramdown 1.5.0
Using liquid 2.6.1
Using mercenary 0.3.5
Using posix-spawn 0.3.9
Using yajl-ruby 1.1.0
Using pygments.rb 0.6.0
Using redcarpet 3.2.1
Using safe_yaml 1.0.4
Using parslet 1.5.0
Using toml 0.1.2
Using jekyll 2.5.2
Using jekyll-sitemap 0.6.3
Using octopress-hooks 2.2.1
Using octopress-date-format 2.0.2
Using rack 1.5.2
Using rack-protection 1.5.3
Using rdiscount 2.1.7.1
Using rubypants 0.2.0
Using sass-globbing 1.0.0
Using sinatra 1.4.5
Using stringex 1.4.0
Using bundler 1.7.8
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

Here the output (error):

``` sh
$ rake generate
## Generating Site with Jekyll
directory source/stylesheets/ 
   create source/stylesheets/screen.css 
  Dependency Error:  Yikes! It looks like you don't have jekyll-coffeescript or one of its dependencies 
installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- json' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
/home/username/.gem/ruby/gems/jekyll-2.5.2/lib/jekyll/deprecator.rb:56:in `rescue in block in gracefully_require': jekyll-coffeescript (Jekyll::Errors::MissingDependencyException)
  from /home/username/.gem/ruby/gems/jekyll-2.5.2/lib/jekyll/deprecator.rb:45:in `block in gracefully_require'
  from /home/username/.gem/ruby/gems/jekyll-2.5.2/lib/jekyll/deprecator.rb:44:in `each'
  from /home/username/.gem/ruby/gems/jekyll-2.5.2/lib/jekyll/deprecator.rb:44:in `gracefully_require'
  from /home/username/.gem/ruby/gems/jekyll-2.5.2/lib/jekyll.rb:166:in `<top (required)>'
  from /home/username/.gem/ruby/gems/jekyll-2.5.2/bin/jekyll:6:in `require'
  from /home/username/.gem/ruby/gems/jekyll-2.5.2/bin/jekyll:6:in `<top (required)>'
  from /home/username/bin/jekyll:23:in `load'
  from /home/username/bin/jekyll:23:in `<main>'
```

But `jekyll-coffeescript` is installed:

``` sh
$ bundle show jekyll-coffeescript
/home/username/.gem/ruby/gems/jekyll-coffeescript-1.0.1
```

I can't find the error.

Thanks in advance!

**Comment by gracca** [comment]
I have a similar issue in Fedora 21. I have added `json` to Gemfile, but now I got the following error:

```shell
german@skytux octopress $ rake generate
## Generating Site with Jekyll
    write source/stylesheets/screen.css
Configuration file: /home/german/github/octopress/_config.yml
/home/german/.gem/ruby/gems/yajl-ruby-1.1.0/lib/yajl.rb:1:in `require': libruby.so.2.0: cannot open shared object file: No such file or directory - /home/german/.gem/ruby/gems/yajl-ruby-1.1.0/lib/yajl/yajl.so (LoadError)
	from /home/german/.gem/ruby/gems/yajl-ruby-1.1.0/lib/yajl.rb:1:in `<top (required)>'
	from /home/german/.gem/ruby/gems/pygments.rb-0.6.0/lib/pygments/popen.rb:3:in `require'
	from /home/german/.gem/ruby/gems/pygments.rb-0.6.0/lib/pygments/popen.rb:3:in `<top (required)>'
	from /home/german/.gem/ruby/gems/pygments.rb-0.6.0/lib/pygments.rb:1:in `require'
	from /home/german/.gem/ruby/gems/pygments.rb-0.6.0/lib/pygments.rb:1:in `<top (required)>'
	from /home/german/github/octopress/plugins/pygments_code.rb:1:in `require'
	from /home/german/github/octopress/plugins/pygments_code.rb:1:in `<top (required)>'
	from /home/german/github/octopress/plugins/backtick_code_block.rb:1:in `require'
	from /home/german/github/octopress/plugins/backtick_code_block.rb:1:in `<top (required)>'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:74:in `require'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:74:in `block (2 levels) in require_plugin_files'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:73:in `each'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:73:in `block in require_plugin_files'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:72:in `each'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:72:in `require_plugin_files'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `new'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `process'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /home/german/bin/jekyll:23:in `load'
	from /home/german/bin/jekyll:23:in `<main>'
```
Any help on this?

**Comment by dmbaturin** [comment]
I wanted to install octopress and I've hit this exact issues as well, on Fedora 21. Any updates on it?

**Comment by NightKs** [comment]
When I run jekyll serve, I got the following problem,
Dependency Error: Yikes! It looks like you don't have rdiscount or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- rdiscount' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2015-12-12-welcome-to-jekyll.markdown':
                    rdiscount
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    rdiscount

Would you give me some suggestion? Thank you！！！
