### ISSUE TITLE
[3.0.0.rc.30] Is the new octopress 2.2.0 compatible?

### ISSUE THREAD

**Issue by keltia** [imathis/octopress#1712]
OS X 10.10.1, clang 3.5, ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14].

Hello, 

Everytime I run octopress, I get this error message:

    /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/safe_yaml-1.0.3/lib/safe_yaml/load.rb:43:in `<module:SafeYAML>': undefined method `tagged_classes' for Psych:Module (NoMethodError)
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/safe_yaml-1.0.3/lib/safe_yaml/load.rb:26:in `<top (required)>'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll.rb:26:in `<top (required)>'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/octopress-3.0.0.rc.30/lib/octopress/command.rb:1:in `<top (required)>'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/octopress-3.0.0.rc.30/lib/octopress.rb:5:in `<module:Octopress>'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/octopress-3.0.0.rc.30/lib/octopress.rb:4:in `<top (required)>'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/octopress-3.0.0.rc.30/bin/octopress:6:in `<top (required)>'
	from /Users/roberto/.rbenv/versions/2.2.0/bin/octopress:23:in `load'
	from /Users/roberto/.rbenv/versions/2.2.0/bin/octopress:23:in `<main>'

does that mean that it can't be run under 2.2.0?

**Comment by keltia** [comment]
Moved to octopress/octopress.
