### ISSUE TITLE
error with 'rake generate'

### ISSUE THREAD

**Issue by gracca** [imathis/octopress#1747]
I'm not able to see the changes in my blog. Please advise!

```bash
$ rake generate
## Generating Site with Jekyll
/home/german/.gem/ruby/gems/compass-core-1.0.1/lib/compass/core/caniuse.rb:72: warning: circular argument reference - browsers
    write source/stylesheets/screen.css
/home/german/.gem/ruby/gems/liquid-2.6.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"
Configuration file: /home/german/github/octopress/_config.yml
/home/german/.gem/ruby/gems/posix-spawn-0.3.9/lib/posix/spawn.rb:2:in `require': cannot load such file -- posix_spawn_ext (LoadError)
	from /home/german/.gem/ruby/gems/posix-spawn-0.3.9/lib/posix/spawn.rb:2:in `<top (required)>'
	from /home/german/.gem/ruby/gems/pygments.rb-0.6.0/lib/pygments/popen.rb:2:in `require'
	from /home/german/.gem/ruby/gems/pygments.rb-0.6.0/lib/pygments/popen.rb:2:in `<top (required)>'
	from /home/german/.gem/ruby/gems/pygments.rb-0.6.0/lib/pygments.rb:1:in `require'
	from /home/german/.gem/ruby/gems/pygments.rb-0.6.0/lib/pygments.rb:1:in `<top (required)>'
	from /home/german/github/octopress/plugins/pygments_code.rb:1:in `require'
	from /home/german/github/octopress/plugins/pygments_code.rb:1:in `<top (required)>'
	from /home/german/github/octopress/plugins/backtick_code_block.rb:1:in `require'
	from /home/german/github/octopress/plugins/backtick_code_block.rb:1:in `<top (required)>'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:74:in `require'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:74:in `block (2 levels) in require_plugin_files'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:73:in `each'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:73:in `block in require_plugin_files'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:72:in `each'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:72:in `require_plugin_files'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `new'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `process'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /home/german/bin/jekyll:23:in `load'
	from /home/german/bin/jekyll:23:in `<main>'

```

**Comment by parkr** [comment]
Try with `bundle exec rake generate`.

**Comment by gracca** [comment]
```bash
$ bundle exec rake generate
## Generating Site with Jekyll
/home/german/.gem/ruby/gems/compass-core-1.0.1/lib/compass/core/caniuse.rb:72: warning: circular argument reference - browsers
    write source/stylesheets/screen.css
/home/german/.gem/ruby/gems/liquid-2.6.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"
Configuration file: /home/german/github/octopress/_config.yml
/home/german/.gem/ruby/gems/posix-spawn-0.3.9/lib/posix/spawn.rb:2:in `require': cannot load such file -- posix_spawn_ext (LoadError)
	from /home/german/.gem/ruby/gems/posix-spawn-0.3.9/lib/posix/spawn.rb:2:in `<top (required)>'
	from /home/german/.gem/ruby/gems/pygments.rb-0.6.0/lib/pygments/popen.rb:2:in `require'
	from /home/german/.gem/ruby/gems/pygments.rb-0.6.0/lib/pygments/popen.rb:2:in `<top (required)>'
	from /home/german/.gem/ruby/gems/pygments.rb-0.6.0/lib/pygments.rb:1:in `require'
	from /home/german/.gem/ruby/gems/pygments.rb-0.6.0/lib/pygments.rb:1:in `<top (required)>'
	from /home/german/github/octopress/plugins/pygments_code.rb:1:in `require'
	from /home/german/github/octopress/plugins/pygments_code.rb:1:in `<top (required)>'
	from /home/german/github/octopress/plugins/backtick_code_block.rb:1:in `require'
	from /home/german/github/octopress/plugins/backtick_code_block.rb:1:in `<top (required)>'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:74:in `require'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:74:in `block (2 levels) in require_plugin_files'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:73:in `each'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:73:in `block in require_plugin_files'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:72:in `each'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:72:in `require_plugin_files'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `new'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `process'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /home/german/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /home/german/.gem/ruby/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /home/german/bin/jekyll:23:in `load'
	from /home/german/bin/jekyll:23:in `<main>'
```

**Comment by parkr** [comment]
There was a problem installing posix-spawn. Try running `bundle install` again.

**Comment by gracca** [comment]
I already did it when I updated octopress following the instructions here: http://octopress.org/docs/updating/

I did it again, but still no luck, same errors as before.

```bash
$ bundle install
Using rake (10.4.2) 
Using RedCloth (4.2.9) 
Using blankslate (2.1.2.4) 
Using hitimes (1.2.2) 
Using timers (4.0.1) 
Using celluloid (0.16.0) 
Using chunky_png (1.3.3) 
Using fast-stemmer (1.0.2) 
Using classifier-reborn (2.0.3) 
Using coffee-script-source (1.8.0) 
Using execjs (2.2.2) 
Using coffee-script (2.3.0) 
Using colorator (0.1) 
Using multi_json (1.10.1) 
Using sass (3.4.9) 
Using compass-core (1.0.1) 
Using compass-import-once (1.0.5) 
Using rb-fsevent (0.9.4) 
Using ffi (1.9.6) 
Using rb-inotify (0.9.5) 
Using compass (1.0.1) 
Using tilt (1.4.1) 
Using haml (4.0.6) 
Using jekyll-coffeescript (1.0.1) 
Using jekyll-gist (1.1.0) 
Using jekyll-paginate (1.1.0) 
Using jekyll-sass-converter (1.3.0) 
Using listen (2.8.4) 
Using jekyll-watch (1.2.0) 
Using kramdown (1.5.0) 
Using liquid (2.6.1) 
Using mercenary (0.3.5) 
Using posix-spawn (0.3.9) 
Using yajl-ruby (1.1.0) 
Using pygments.rb (0.6.0) 
Using redcarpet (3.2.2) 
Using safe_yaml (1.0.4) 
Using parslet (1.5.0) 
Using toml (0.1.2) 
Using jekyll (2.5.3) 
Using jekyll-sitemap (0.7.0) 
Using json (1.8.1) 
Using octopress-hooks (2.2.3) 
Using octopress-date-format (2.0.2) 
Using rack (1.6.0) 
Using rack-protection (1.5.3) 
Using rdiscount (2.1.7.1) 
Using sass-globbing (1.0.0) 
Using sinatra (1.4.5) 
Using stringex (1.4.0) 
Using bundler (1.3.5) 
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

**Comment by parkr** [comment]
Try: `gem uninstall posix-spawn; gem install posix-spawn`.

**Comment by gracca** [comment]
Didn't work. See the steps here:

http://fpaste.org/271861/43303744/

**Comment by parkr** [comment]
This is likely an environment problem. Bundle may not be looking

**Comment by gracca** [comment]
@parkr thanks for your support! Can you still help me on this problem? Thing is that I don't understand anything about Ruby!
