### ISSUE TITLE
rake generate error:Yikes! It looks like you don't have jekyll-coffeescript or one of its dependencies installed.

### ISSUE THREAD

**Issue by jakoo** [imathis/octopress#1752]
This error came out after I used "rake generate". Adding  `gem 'json'` to Gemfile doesn't help.
```shell
$ rake generate
## Generating Site with Jekyll
    write source/stylesheets/screen.css
  Dependency Error:  Yikes! It looks like you don't have jekyll-coffeescript or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- json/pure' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
/home/username/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:56:in `rescue in block in gracefully_require': jekyll-coffeescript (Jekyll::Errors::MissingDependencyException)
	from /home/username/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:45:in `block in gracefully_require'
	from /home/username/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:44:in `each'
	from /home/username/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:44:in `gracefully_require'
	from /home/username/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll.rb:166:in `<top (required)>'
	from /home/username/.gem/ruby/gems/jekyll-2.5.3/bin/jekyll:6:in `require'
	from /home/username/.gem/ruby/gems/jekyll-2.5.3/bin/jekyll:6:in `<top (required)>'
	from /home/username/bin/jekyll:23:in `load'
	from /home/username/bin/jekyll:23:in `<main>'
```

```shell
$ bundle show jekyll-coffeescript
/home/username/.gem/ruby/gems/jekyll-coffeescript-1.0.1
```
I'm using fedora20 + zsh. Anyone know how to solve this problem? Thanks in advanced.

**Comment by erizhang** [comment]
exactly same problem I encounter....

**Comment by erizhang** [comment]
Add `gem 'json_pure'` in the `Gemfile`, previous error message has been resolved, but there is another message prompts:
```
## Generating Site with Jekyll
identical source/stylesheets/screen.css
/home/erizhang/.gem/ruby/gems/execjs-2.6.0/lib/execjs/runtimes.rb:48:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
        from /home/erizhang/.gem/ruby/gems/execjs-2.6.0/lib/execjs.rb:5:in `<module:ExecJS>'
        from /home/erizhang/.gem/ruby/gems/execjs-2.6.0/lib/execjs.rb:4:in `<top (required)>'
        from /home/erizhang/.gem/ruby/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `require'
        from /home/erizhang/.gem/ruby/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `<top (required)>'
        from /home/erizhang/.gem/ruby/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `require'
        from /home/erizhang/.gem/ruby/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `<top (required)>'
        from /home/erizhang/.gem/ruby/gems/jekyll-coffeescript-1.0.1/lib/jekyll-coffeescript.rb:2:in `require'
        from /home/erizhang/.gem/ruby/gems/jekyll-coffeescript-1.0.1/lib/jekyll-coffeescript.rb:2:in `<top (required)>'
        from /home/erizhang/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:46:in `require'
        from /home/erizhang/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:46:in `block in gracefully_require'
        from /home/erizhang/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:44:in `each'
        from /home/erizhang/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:44:in `gracefully_require'
        from /home/erizhang/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll.rb:166:in `<top (required)>'
        from /home/erizhang/.gem/ruby/gems/jekyll-2.5.3/bin/jekyll:6:in `require'
        from /home/erizhang/.gem/ruby/gems/jekyll-2.5.3/bin/jekyll:6:in `<top (required)>'
        from /home/erizhang/bin/jekyll:23:in `load'
        from /home/erizhang/bin/jekyll:23:in `<main>'

```

**Comment by tvieira** [comment]
Got the same problem with F22 and @erizhang solution solved it. Thanks.

**Comment by docsteveharris** [comment]
@erizhang solved it for me too - thanks
